"use client";
import {useEffect,useState} from 'react';
import {Upload,Download,Printer,BarChart3,Building2,Layers3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {ChartContainer} from '@/components/ui/chart';
import {BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,LineChart,Line} from 'recharts';
import initial from '@/data/initial.json';
import {analyze,normalizeRows,type Snapshot,type Vendor} from '@/lib/analysis';
const baseline:Snapshot={id:'initial-115',label:'115年原始統計',period:'',kind:'未確認',source:'115年廠商年度統計表.xlsx',rows:initial,createdAt:''};
const number=(v:number)=>v.toLocaleString('zh-TW',{maximumFractionDigits:2});
const pct=(v:number)=>(v*100).toFixed(2)+'%';
export default function Dashboard(){
 const [snapshots,setSnapshots]=useState<Snapshot[]>([baseline]),[selected,setSelected]=useState(baseline.id),[compare,setCompare]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[draft,setDraft]=useState<Vendor[]>([]),[file,setFile]=useState(''),[label,setLabel]=useState(''),[period,setPeriod]=useState(''),[kind,setKind]=useState('累計'),[busy,setBusy]=useState(false),[importError,setImportError]=useState(''),[notice,setNotice]=useState(''),[showAll,setShowAll]=useState(false),[requestId,setRequestId]=useState('');
 async function refresh(){setLoading(true);try{const r=await fetch('/api/snapshots',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setSnapshots([baseline,...d.snapshots]);setError('');}catch(e){setError(e instanceof Error?e.message:'讀取失敗');}finally{setLoading(false);}}
 useEffect(()=>{refresh()},[]);
 const current=snapshots.find(s=>s.id===selected)||baseline,prior=snapshots.find(s=>s.id===compare),a=analyze(current.rows),b=prior?analyze(prior.rows):null,previous=new Map(b?.rows.map(r=>[r.name,r])||[]);
 const delta=b?a.total-b.total:null,shown=showAll?a.rows:a.rows.slice(0,10),missing=b?.rows.filter(r=>!a.rows.some(s=>s.name===r.name))||[];
 const history=snapshots.filter(s=>s.period&&s.kind===current.kind).sort((x,y)=>x.period.localeCompare(y.period)||x.createdAt.localeCompare(y.createdAt)).map(s=>({label:s.label,amount:analyze(s.rows).total}));
 async function readFile(f:File){setImportError('');setDraft([]);setFile(f.name);if(f.size>5*1024*1024){setImportError('檔案請小於5MB。');return;}setBusy(true);try{const XLSX=await import('xlsx');const w=XLSX.read(await f.arrayBuffer(),{type:'array'});const grid=XLSX.utils.sheet_to_json<any[]>(w.Sheets[w.SheetNames[0]],{header:1,defval:''});const hi=grid.findIndex(r=>r.includes('廠商簡稱')&&r.includes('總計金額'));if(hi<0)throw new Error('第一張工作表須包含「廠商簡稱」與「總計金額」欄位。');const nc=grid[hi].indexOf('廠商簡稱'),ac=grid[hi].indexOf('總計金額');const rows:Vendor[]=[];for(let i=hi+1;i<grid.length;i++){const r=grid[i];if(r.every(v=>v===''))continue;const name=String(r[nc]).trim();if(/^(總計|合計|小計)$/.test(name))continue;const raw=r[ac];if(raw===''||raw===null||raw===undefined)throw new Error(`第${i+1}列缺少金額。`);const amount=typeof raw==='number'?raw:Number(String(raw).replace(/,/g,''));rows.push({name,amount});}setDraft(normalizeRows(rows));setLabel(f.name.replace(/\.(xlsx|csv)$/i,''));setRequestId(crypto.randomUUID());}catch(e){setImportError(e instanceof Error?e.message:'無法讀取檔案。')}finally{setBusy(false)}}
 async function save(){setBusy(true);setImportError('');try{if(!period||!label.trim())throw new Error('請填寫期間名稱及統計截止日。');const r=await fetch('/api/snapshots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId,label,period,kind,source:file,rows:draft})}),d:any=await r.json();if(!r.ok)throw new Error(d.error);await refresh();setSelected(requestId);setCompare(current.id);setOpen(false);setDraft([]);setNotice('新版本已儲存，可切換期間查看。');}catch(e){setImportError(e instanceof Error?e.message:'儲存失敗')}finally{setBusy(false)}}
 function exportCsv(){const cell=(v:unknown)=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const rows=[['期間',current.label],['統計口徑',current.kind],['統計截止日',current.period||'未確認'],['排名','廠商簡稱','總計金額','占比','累計占比','ABC'],...a.rows.map(r=>[r.rank,r.name,r.amount,pct(r.share),pct(r.cumulative),r.group])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const el=document.createElement('a');el.href=url;el.download=current.label+'-採購排名.csv';el.click();URL.revokeObjectURL(url);}
 return <><header className="topbar"><div className="brand"><span className="brand-icon"><BarChart3 size={23}/></span>採購管理<span className="brand-sub">經營分析</span></div><span className="top-meta">廠商 · 金額 · 變化</span></header><main><div className="page-heading"><div><p className="eyebrow">PROCUREMENT OVERVIEW</p><h1>採購管理總覽</h1><p className="muted">掌握主要供應商，讓每次採購都有依據。</p></div><div className="actions"><Button variant="outline" onClick={()=>window.print()}><Printer/>列印報告</Button><Button onClick={()=>{setImportError('');setOpen(true)}}><Upload/>匯入統計表</Button></div></div>
 <div className="toolbar"><label>檢視期間<select value={selected} onChange={e=>{setSelected(e.target.value);setShowAll(false);if(e.target.value===compare)setCompare('')}}>{snapshots.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>比較基準<select value={compare} onChange={e=>setCompare(e.target.value)}><option value="">不比較</option>{snapshots.filter(s=>s.id!==selected).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><div className="period-meta"><span>{current.kind==='未確認'?'統計口徑待確認':current.kind+'統計'}</span><small>{current.period?'截至 '+current.period:'截止日未提供'}</small></div></div>
 {loading&&<p role="status" className="message">正在讀取歷期資料…</p>}{error&&<div role="alert" className="message warning">{error} 目前仍可查看原始統計。<Button variant="outline" onClick={refresh}>重新讀取</Button></div>}{notice&&<p role="status" className="message">{notice}</p>}
 {prior&&<p className="comparison-note">比較：{current.label} 與 {prior.label}。{current.kind!==prior.kind?'兩份資料的統計口徑不同，差額僅供核對，不代表成長率。':'請確認兩期涵蓋範圍一致；累計版本差額不等同單月採購額。'}</p>}
 <section className="metrics"><article className="metric featured"><span>採購總額</span><strong>{number(a.total)}</strong><small>{delta!==null?`較比較基準 ${delta>=0?'+':''}${number(delta)}`:'依表內金額加總 · 幣別及稅別待確認'}</small></article><article className="metric"><span><Building2 size={17}/>往來廠商</span><strong>{a.rows.length}<em>家</em></strong><small>{b?`較比較基準 ${a.rows.length-b.rows.length>=0?'+':''}${a.rows.length-b.rows.length} 家`:'依廠商簡稱彙整'}</small></article><article className="metric"><span>前十大採購占比</span><strong>{pct(a.top10)}</strong><small>{b?`變動 ${((a.top10-b.top10)*100).toFixed(2)} 個百分點`:'採購金額前10名 / 總採購額'}</small></article><article className="metric"><span><Layers3 size={17}/>涵蓋80%採購額</span><strong>{a.aCount}<em>家</em></strong><small>優先議價與供應管理對象</small></article></section>
 <div className="chart-grid"><section className="panel"><div className="section-title"><div><h2>前十大廠商採購金額</h2><p>依金額由高至低排列</p></div><span className="tag">TOP 10</span></div><ChartContainer config={{amount:{label:'採購金額',color:'#2857d9'}}} className="ranking-chart"><BarChart data={a.rows.slice(0,10)} layout="vertical" margin={{left:8,right:24}}><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number" tickFormatter={v=>number(v/10000)+'萬'} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={108} axisLine={false} tickLine={false} tick={{fontSize:14}}/><Tooltip formatter={(v:any)=>number(Number(v))} cursor={{fill:'#f0f4fc'}}/><Bar dataKey="amount" name="採購金額" fill="#2857d9" radius={[0,4,4,0]} barSize={18}/></BarChart></ChartContainer></section><section className="panel insight"><div className="section-title"><h2>本期採購重點</h2><span className="tag">管理摘要</span></div><div className="focus"><span>第一大供應商</span><h3>{a.rows[0].name}</h3><div className="big-share">{pct(a.rows[0].share)}</div><p>採購金額 {number(a.rows[0].amount)}</p></div><div className="insight-line"><b>01</b><p><strong>集中管理主要廠商</strong>前{a.aCount}家涵蓋{pct(a.rows[a.aCount-1].cumulative)}採購額，優先檢視價格、交期及替代來源。</p></div><div className="insight-line"><b>02</b><p><strong>議價效益試算</strong>前十大同量同規格平均降價1%，約可節省{number(a.total*a.top10*.01)}。此為試算，非已實現效益。</p></div></section></div>
 <section className="panel history"><div className="section-title"><div><h2>歷期金額變化</h2><p>僅呈現相同統計口徑的版本，各期金額不相加</p></div><span className="tag">{current.kind}</span></div>{history.length>=2?<ChartContainer config={{amount:{label:'採購金額',color:'#2857d9'}}} className="history-chart"><LineChart data={history} margin={{left:15,right:25,top:15}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis tickFormatter={v=>number(v/10000)+'萬'}/><Tooltip formatter={(v:any)=>number(Number(v))}/><Line type="linear" dataKey="amount" name="採購金額" stroke="#2857d9" strokeWidth={3} dot={{r:4}}/></LineChart></ChartContainer>:<div className="empty"><BarChart3 size={27}/><div><strong>累積第二期資料，開始追蹤變化</strong><p>匯入相同口徑的資料後，這裡將呈現各版本金額。原始表截止日未確認，暫不納入時間趨勢。</p></div></div>}</section>
 <section className="panel details"><div className="section-title"><div><h2>廠商排名與占比</h2><p>ABC分類依累計金額首次達到80%及95%分界</p></div><Button variant="outline" onClick={exportCsv}><Download/>匯出排名</Button></div><Table><TableHeader><TableRow>{['排名','廠商簡稱','採購金額','占比','累計占比','ABC',...(b?['金額差異','占比差異','排名變化']:[])].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{shown.map(r=>{const old=previous.get(r.name),change=old?old.rank-r.rank:0;return <TableRow key={r.name}><TableCell><span className={'rank '+(r.rank<=3?'leading':'')}>{r.rank}</span></TableCell><TableCell className="vendor-name">{r.name}</TableCell><TableCell>{number(r.amount)}</TableCell><TableCell>{pct(r.share)}</TableCell><TableCell className="muted">{pct(r.cumulative)}</TableCell><TableCell><span className={'abc '+r.group}>{r.group}</span></TableCell>{b&&<><TableCell>{old?`${r.amount-old.amount>=0?'+':''}${number(r.amount-old.amount)}`:'本期新增'}</TableCell><TableCell>{old?((r.share-old.share)*100).toFixed(2)+' pp':'—'}</TableCell><TableCell>{old?change>0?'↑ '+change:change<0?'↓ '+(-change):'持平':'新增'}</TableCell></>}</TableRow>})}</TableBody></Table><div className="table-bottom"><span>顯示 {shown.length} / {a.rows.length} 家</span><Button variant="ghost" onClick={()=>setShowAll(!showAll)}>{showAll?'只顯示前10名':'查看全部廠商'}</Button></div>{missing.length>0&&<p className="comparison-note">比較基準中有{missing.length}家未出現在本期：{missing.map(r=>r.name).join('、')}。未出現不直接視為零採購。</p>}</section>
 <footer><span>來源：{current.source}</span><span>占比＝廠商金額 ÷ 本期總額 · 百分比四捨五入至小數點後兩位</span></footer></main>
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>匯入新的統計版本</DialogTitle><DialogDescription>沿用目前Excel格式，第一張表須有「廠商簡稱」及「總計金額」。每次儲存獨立版本，既有資料會保留。</DialogDescription></DialogHeader><label className="upload-zone">選擇 Excel 或 CSV（上限5MB）<Input type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{if(e.target.files?.[0])readFile(e.target.files[0])}}/></label><div className="form-row"><label>期間名稱<Input value={label} maxLength={80} onChange={e=>setLabel(e.target.value)} placeholder="例如：115年1–9月累計"/></label><label>統計截止日<Input type="date" value={period} onChange={e=>setPeriod(e.target.value)}/></label></div><label>統計口徑<select value={kind} onChange={e=>setKind(e.target.value)}><option>累計</option><option>單期</option><option>年度</option></select></label><p className="muted">累計：年初至截止日；單期：單月或單季；年度：已結算全年。同名廠商會合併，標記為總計、合計、小計的列會略過。金額須為非負數；請使用一致幣別與稅別。</p>{draft.length>0&&<div className="import-preview"><strong>匯入預覽：{draft.length}家 · 總額 {number(analyze(draft).total)}</strong><p>最大廠商：{draft[0].name} · {number(draft[0].amount)}</p><small>請確認不是誤選已匯入的檔案；儲存後可隨時切換版本。</small></div>}{importError&&<p role="alert" className="warning">{importError}</p>}<Button disabled={busy||!draft.length||!label.trim()||!period} onClick={save}>{busy?'處理中…':'確認並儲存新版本'}</Button></DialogContent></Dialog></>;
}

